### ISSUE TITLE
Create basic project structure

### ISSUE THREAD

**Issue by GustavoCig** [GustavoCig/data-vis_brasileirao#1]
Add a commit that adds a basic structure to the project.
For example:
project_root
htmls
-js/
-css/
-data/

**Comment by diogofm** [comment]
I think that the HTML folder shouldn't exist.
I would be easier if the HTML files were inside project root.

**Comment by GustavoCig** [comment]
Sure, that works as well

**Comment by GustavoCig** [comment]
Also, just as an extra.
Any assets besides js, css, datasets and htmls, should be stored in a separate assets folder.
Ao the structure ends up like this:
project_root
  htmls
  -js/
  -css/
  -data/
  -assets/

**Comment by GustavoCig** [comment]
Resolved by #42205dd
